### ISSUE TITLE
Window doesn`t show up

### ISSUE THREAD

**Issue by xomax** [erikzielke/GoToProject#3]
GoToProject window doesn`t show up In PHPStorm PS-141.176.

It returns an exception "NoSuchMethodError: com.intellij.ide.RecentProjectsManagerBase.getInstance()Lcom/intellij/ide/RecentProjectsManagerBase;"

Stack trace:
com.intellij.ide.RecentProjectsManagerBase.getInstance()Lcom/intellij/ide/RecentProjectsManagerBase;
java.lang.NoSuchMethodError: com.intellij.ide.RecentProjectsManagerBase.getInstance()Lcom/intellij/ide/RecentProjectsManagerBase;
	at org.github.erikzielke.gotoproject.GoToProject.actionPerformed(GoToProject.java:57)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:576)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:475)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by erikzielke** [comment]
Should be fixed now
